//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDevletBildirimService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/", ConfigurationName="EDevletBildirimService.Notification")]
    public interface Notification
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.notification.turkiye.gov.tr/v2/sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generalOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generalInputType))]
        System.Threading.Tasks.Task<EDevletBildirimService.getReportResponse> getReportAsync(EDevletBildirimService.getReport request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.notification.turkiye.gov.tr/v2/sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generalOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generalInputType))]
        System.Threading.Tasks.Task<EDevletBildirimService.sendMessageResponse> sendMessageAsync(EDevletBildirimService.sendMessage request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class campaignReportInput : generalInputType
    {
        
        private string campaignIdField;
        
        private string startDateField;
        
        private string finishDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string campaignId
        {
            get
            {
                return this.campaignIdField;
            }
            set
            {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string finishDate
        {
            get
            {
                return this.finishDateField;
            }
            set
            {
                this.finishDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignReportInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class generalInputType
    {
        
        private int corporationCodeField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int corporationCode
        {
            get
            {
                return this.corporationCodeField;
            }
            set
            {
                this.corporationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class campaignNotificationCount
    {
        
        private long bouncedNotificationField;
        
        private bool bouncedNotificationFieldSpecified;
        
        private long inprogressNotificationField;
        
        private bool inprogressNotificationFieldSpecified;
        
        private long successfulNotificationField;
        
        private bool successfulNotificationFieldSpecified;
        
        private long totalNotificationRequestField;
        
        private bool totalNotificationRequestFieldSpecified;
        
        private long unsuccessfulNotificationField;
        
        private bool unsuccessfulNotificationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long bouncedNotification
        {
            get
            {
                return this.bouncedNotificationField;
            }
            set
            {
                this.bouncedNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bouncedNotificationSpecified
        {
            get
            {
                return this.bouncedNotificationFieldSpecified;
            }
            set
            {
                this.bouncedNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long inprogressNotification
        {
            get
            {
                return this.inprogressNotificationField;
            }
            set
            {
                this.inprogressNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inprogressNotificationSpecified
        {
            get
            {
                return this.inprogressNotificationFieldSpecified;
            }
            set
            {
                this.inprogressNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long successfulNotification
        {
            get
            {
                return this.successfulNotificationField;
            }
            set
            {
                this.successfulNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successfulNotificationSpecified
        {
            get
            {
                return this.successfulNotificationFieldSpecified;
            }
            set
            {
                this.successfulNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long totalNotificationRequest
        {
            get
            {
                return this.totalNotificationRequestField;
            }
            set
            {
                this.totalNotificationRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalNotificationRequestSpecified
        {
            get
            {
                return this.totalNotificationRequestFieldSpecified;
            }
            set
            {
                this.totalNotificationRequestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long unsuccessfulNotification
        {
            get
            {
                return this.unsuccessfulNotificationField;
            }
            set
            {
                this.unsuccessfulNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unsuccessfulNotificationSpecified
        {
            get
            {
                return this.unsuccessfulNotificationFieldSpecified;
            }
            set
            {
                this.unsuccessfulNotificationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendMessageOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(campaignDetailReport))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class generalOutputType
    {
        
        private int corporationCodeField;
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int corporationCode
        {
            get
            {
                return this.corporationCodeField;
            }
            set
            {
                this.corporationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string returnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class sendMessageOutputType : generalOutputType
    {
        
        private System.Nullable<long>[] trackingListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trackingId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<long>[] trackingList
        {
            get
            {
                return this.trackingListField;
            }
            set
            {
                this.trackingListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class campaignDetailReport : generalOutputType
    {
        
        private System.Nullable<long>[] trackingListField;
        
        private campaignNotificationCount statusReportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trackingId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<long>[] trackingList
        {
            get
            {
                return this.trackingListField;
            }
            set
            {
                this.trackingListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public campaignNotificationCount statusReport
        {
            get
            {
                return this.statusReportField;
            }
            set
            {
                this.statusReportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class parameterType
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class msgParameterItemType
    {
        
        private string trIdentityNoField;
        
        private string corporationExternalIdField;
        
        private parameterType[] campaignParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string trIdentityNo
        {
            get
            {
                return this.trIdentityNoField;
            }
            set
            {
                this.trIdentityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string corporationExternalId
        {
            get
            {
                return this.corporationExternalIdField;
            }
            set
            {
                this.corporationExternalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parameterType[] campaignParameters
        {
            get
            {
                return this.campaignParametersField;
            }
            set
            {
                this.campaignParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/")]
    public partial class campaignMessage : generalInputType
    {
        
        private string campaignIdField;
        
        private msgParameterItemType[] messageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string campaignId
        {
            get
            {
                return this.campaignIdField;
            }
            set
            {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public msgParameterItemType[] messageList
        {
            get
            {
                return this.messageListField;
            }
            set
            {
                this.messageListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReport
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EDevletBildirimService.campaignReportInput getReportG;
        
        public getReport()
        {
        }
        
        public getReport(EDevletBildirimService.campaignReportInput getReportG)
        {
            this.getReportG = getReportG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EDevletBildirimService.campaignDetailReport getReportC;
        
        public getReportResponse()
        {
        }
        
        public getReportResponse(EDevletBildirimService.campaignDetailReport getReportC)
        {
            this.getReportC = getReportC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/", Order=0)]
        public EDevletBildirimService.campaignMessage sendMessageG;
        
        public sendMessage()
        {
        }
        
        public sendMessage(EDevletBildirimService.campaignMessage sendMessageG)
        {
            this.sendMessageG = sendMessageG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.notification.turkiye.gov.tr/v2/", Order=0)]
        public EDevletBildirimService.sendMessageOutputType sendMessageC;
        
        public sendMessageResponse()
        {
        }
        
        public sendMessageResponse(EDevletBildirimService.sendMessageOutputType sendMessageC)
        {
            this.sendMessageC = sendMessageC;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface NotificationChannel : EDevletBildirimService.Notification, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class NotificationClient : System.ServiceModel.ClientBase<EDevletBildirimService.Notification>, EDevletBildirimService.Notification
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationClient() : 
                base(NotificationClient.GetDefaultBinding(), NotificationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NotificationPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationClient.GetBindingForEndpoint(endpointConfiguration), NotificationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDevletBildirimService.getReportResponse> EDevletBildirimService.Notification.getReportAsync(EDevletBildirimService.getReport request)
        {
            return base.Channel.getReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDevletBildirimService.getReportResponse> getReportAsync(EDevletBildirimService.campaignReportInput getReportG)
        {
            EDevletBildirimService.getReport inValue = new EDevletBildirimService.getReport();
            inValue.getReportG = getReportG;
            return ((EDevletBildirimService.Notification)(this)).getReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDevletBildirimService.sendMessageResponse> EDevletBildirimService.Notification.sendMessageAsync(EDevletBildirimService.sendMessage request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDevletBildirimService.sendMessageResponse> sendMessageAsync(EDevletBildirimService.campaignMessage sendMessageG)
        {
            EDevletBildirimService.sendMessage inValue = new EDevletBildirimService.sendMessage();
            inValue.sendMessageG = sendMessageG;
            return ((EDevletBildirimService.Notification)(this)).sendMessageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificationPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificationPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.101.55.17:8282/services/edevlet/bildirim");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotificationClient.GetBindingForEndpoint(EndpointConfiguration.NotificationPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotificationClient.GetEndpointAddress(EndpointConfiguration.NotificationPort);
        }
        
        public enum EndpointConfiguration
        {
            
            NotificationPort,
        }
    }
}
